name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
      - stage
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using Service Account JSON secret
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up the Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      # Configure Docker to authenticate with Google Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      # Build and push Docker image to Artifact Registry
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/groq-chat-repo/${{ vars.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
          gcloud builds submit --tag $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.CLOUD_RUN_SERVICE_NAME }} \
            --image $IMAGE_URI \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }} \
            --set-secrets GROQ_API_KEY=groq-api-key:latest
